### ISSUE TITLE
Dude my account got disabled :((((

### ISSUE THREAD

**Issue by bash0x0** [sql69/sql69#1]
Dude my account got disabled :((((

**Comment by sql69** [comment]
WHAT

**Comment by sql69** [comment]
SAME

**Comment by sql69** [comment]
bro add my discord

**Comment by sql69** [comment]
devs#9416

**Comment by bash0x0** [comment]
i think everyone from nightfalls discord got termed

**Comment by bash0x0** [comment]
discord not cool, imma go back to teamspeak bro :(
